part of values;

class Assets {
  static final String fontFamily = "roboto";
  //static final String testLottie = "assets/test_lottie.json";
  static final String dashBoard = "assets/dashboard.svg";
  static final String watch = "assets/watch.svg";
  static final String media = "assets/media.svg";
  static final String locationScreen = "assets/location_screen.svg";
  static final String referFriend1 = "assets/refer_friend.svg";
  static final String imgAfterNoon = "assets/afternoon.png";
  static final String imgNight = "assets/night.png";
  static final String closeBlackArrow = "assets/close_black_arrow.svg";
  static final String clearSearch = "assets/clear_search.svg";
  static final String closeBlackCross = "assets/cross_black.svg";
  static final String backArrowWhite = "assets/back_arrow_white.svg";
  static final String backArrowCs = "assets/back_arrow_cs.svg";
  static final String icWatch = "assets/ic_watch_trailer.svg";
  static final String currentLocation = "assets/current_location.svg";
  static final String dottedBorderSelected = "assets/dotted_selected.svg";
  static final String dottedBorderNotSelected = "assets/dotted_notselected.svg";
  static final String iclocation = "assets/location.svg";
  static final String like = "assets/like.svg";
  static final String leafCounter = "assets/leafcs.svg";
  static final String leafCsDisable = "assets/leaf_cs_disable.svg";
  static final String disLike = "assets/dislike.svg";
  static final String labaiikLightLogo = "assets/labaiik_light.svg";
  static final String fabLabaiik = "assets/fab_labaiik.svg";
  static final String nolocationLogo = "assets/nolocationlogo.svg";
  static final String leftMenuIconHome = "assets/home_icon_left_menu.svg";
  static final String noInternet = "assets/no_internet.svg";
  static final String noStoreAvailable = "assets/no_store_available.svg";
  static final String leftMenuIconMyOrders = "assets/my_orders_left_menu.svg";
  static final String leftMenuIconPaymentMethods =
      "assets/payment_methods_left_menu.svg";
  static final String leftMenuIconManageAddress =
      "assets/mange_address_left_menu.svg";
  static final String leftMenuIconReferFriend =
      "assets/refer_your_friend_left_menu.svg";
  static final String leftMenuIconHelpCenter =
      "assets/help_center_left_menu.svg";
  static final String addNewCardIcon = "assets/add_new_card_icon.svg";
  static final String leftMenuIconSetting = "assets/setting.svg";
  static final String masterCardIcon = "assets/master_card_icon.svg";
  static final String visaCardIcon = "assets/visa_card.svg";
  static final String currentCardIcon = "assets/current_card_icon.svg";
  static final String notSelectedCardIcon = "assets/card_icon_not_selected.svg";
  static final String ic_cart_action = "assets/ic_cart_action.svg";
  static final String chipIcon = "assets/sim_card.svg";
  static final String locationIcon = "assets/location_icon.svg";
  static final String locationPicker = "assets/location_picker_icon.svg";
  static final String crossBlack = "assets/cross_black.svg";
  static final String referFriend = "assets/refer_friend_screen_icon.svg";
  static final String placeOrderIcon = "assets/place_order_icon.svg";
  static final String orderCancelled = "assets/order_cancelled.svg";
  static final String orderCompleted = "assets/order_completed.svg";
  static final String orderDeliverOn = "assets/order_deliver_on.svg";
  static final String orderPickByDriver = "assets/pick_by_driver.svg";
  static final String driverAtDeliveryLocation =
      "assets/driver_at_delivery_location.svg";
  static final String deleteIcon = "assets/delete_icon.svg";
  static final String dottedBorder = "assets/dotted_border.svg";
  static final String arrowForward = "assets/arrow_forward.svg";
  static final String profileIcon = "assets/profile_icon.svg";
  static final String signOut = "assets/sign_out_icon.svg";
  static final String deleteIconCard = "assets/delete_icon_card.svg";
  static final String termsConditionIcon = "assets/terms_condition_icon.svg";
  static final String privacyPolicyIcon = "assets/privacy_policy_icon.svg";
  static final String editProfileIcon = "assets/edit_profile_icon.svg";
  static final String chatIcon = "assets/chat_icon.svg";
  static final String assignedDriverIcon = "assets/assigned_driver_icon.svg";
  static final String chatIconClick = "assets/chat_icon_click.svg";
  static final String callIcon = "assets/call_icon.svg";
  static final String routeIcon = "assets/route_icon.svg";
  static final String ic_heart_red = "assets/ic_heart_red.svg";
  static final String ic_heart_top = "assets/fav_icon.svg";
  static final String ic_heart_top1 = "assets/ic_heart_top.svg";
  static final String ic_filter = "assets/ic_filter.svg";
  static final String filter = "assets/filter.svg";
  static final String ic_clock_icon = "assets/clock_icon.svg";
  static final String ic_heart = "assets/ic_heart.svg";
  static final String ic_location_pin = "assets/time_icon_new1.svg";
  static final String ic_search = "assets/ic_search.svg";
  static final String ic_expanded = "assets/ic_expanded.svg";
  static final String ic_row = "assets/ic_row.svg";
  static final String ic_time = "assets/time.svg";
  static final String ic_minorder = "assets/min_order_new.svg";
  static final String currentLocationIcon = "assets/current_location_icon.svg";
  static final String unfilledRadioIcon = "assets/unfilled_radio_icon.svg";
  static final String filledRadioIcon = "assets/filled_radio_icon.svg";
  static final String filledCheckBoxIcon = "assets/filled_checkbox_icon.svg";
  static final String dottedLine = "assets/dotted_line.svg";
  static final String deliveryIcon = "assets/delivery_icon.svg";
  static final String upKeyBoard = "assets/up_keyboard.svg";
  static final String downKeyBoard = "assets/down_keyboard.svg";
  static final String orderSuccessBox = "assets/order_success_box.svg";
  static final String greenDotIcon = "assets/green_dot_icon.svg";
  static final String emptyOrderBox = "assets/empty_order_box.svg";
  static final String splashGif = "assets/labaiik_splash_screen_green.gif";
  static final String splashGifNew = "assets/labaiik_gif_updated.gif";
//  static final String icMenu = "assets/ic_menu.svg";
  static final String icMenu = "assets/ic_menu_new.svg";
  static final String icMenuBackground = "assets/menu_background.svg";
  static final String icMenuBackgroundBanner = "assets/menu_background_banner.svg";
  static final String category_banner = "assets/Category_background.svg";
  static final String chatIconBlack = "assets/chat_icon_black.svg";
  static final String noProductIcon = "assets/no_product.svg";
  static final String minOrder = "assets/min_order.svg";
  static final String countryPickerDropDown = "assets/drop_down_phone.svg";
  static final String ratingBack = "assets/rating_back.svg";
  static final String ratingDown = "assets/rating_down.svg";
  static final String filledStar = "assets/filled_star.svg";
  static final String emptyStar = "assets/empty_star.svg";
  static final String countDownTimerIcon = "assets/timer_icon.svg";
  static final String paymentFailedIcon = "assets/payment_failed.svg";
  static final String liveGif = "assets/live.gif";
  static final String icAddressError = "assets/ic_empty_address_error.svg";
  static final String ic_subtracts = "assets/ic_subtract.svg";
  // static final String ic_promo_avail_mask = "assets/promo_code_avaliable_mask.png";
  static final String ic_promo_avail_mask = "assets/ic_promo_background.png";
  static final String ic_additional_notes = "assets/additional_notes.svg";
  static final String ic_pay_using = "assets/ic_pay_using.svg";
  static final String ic_nopromotion_available =
      "assets/no_promotion_available.svg";

  static final String cashDeliveryIcon = "assets/delivery_cash_icon.svg";
  static final String americanExpress = "assets/american_express.svg";
  static final String crossBackIcon = 'assets/cross_back.svg';
  static final String myLocationIcon = 'assets/my_location_icon.svg';
  static final String locationPinIcon = 'assets/location_pin.svg';
  static final String editPencil = 'assets/edit_pencil.svg';
  static final String pinIcon = 'assets/pin.svg';
  static final String greenTickIcon = 'assets/green_tick.svg';
  static final String uncheckedCircleIcon = 'assets/unchecked_circle.svg';
  static final String homeIcon = 'assets/home.svg';
  static final String workIcon = 'assets/work.svg';
  static final String hotelIcon = 'assets/hotel.svg';
  static final String starIcon = 'assets/star.svg';
  static final String pencilGreen = 'assets/pencil_green.svg';
  static final String circleGreenIcon = 'assets/circle_green.svg';
  static final String emptyAddressIcon = 'assets/no_address.svg';
  static final String myLocationNewIcon = 'assets/my_location_new.svg';
  static final String ic_no_promo = 'assets/ic_no_promo.png';
  static final String cardRemoveIcon = 'assets/card_remove_icon.svg';
  static final String defaultCardIcon = 'assets/default_card_icon.png';

  static final String credits_icon = 'assets/credits_icon.svg';
  static final String credits_bg = 'assets/credits_bg.png';
  static final String copy_icon = 'assets/copy.svg';
  static final String noTransactionHistoryIcon =
      'assets/no_trasaction_history.svg';
  static final String wallet = 'assets/wallet.svg';
  static final String allIcon = 'assets/all_icon.svg';
  // static final String timeIconNew = 'assets/time_icon_new.svg';
  static final String timeIconNew = 'assets/time_icon_new.svg';

  static final String creditsIcon = 'assets/credit.svg';
  static final String reorderIcon = 'assets/reorder_icon.svg';
  static final String updateIcon = 'assets/new_update_icon.svg';
  // static final String superIconTab = 'assets/supermarket_icon.png';
  static final String superIconTab = 'assets/supermarket_tab_icon.png';
  //static final String pharmacyIconTab = 'assets/pharmacy_icon.png';
  static final String pharmacyIconTab = 'assets/pharmacies_tab_icon.png';
  // static final String restaurantIconTab = 'assets/restaurants_icon.png';
  static final String restaurantIconTab = 'assets/restaurant_tab_icon.png';

  static final String infoIcon = 'assets/info_icon.svg';
  static final String plusIcon = 'assets/plus_icon.svg';
  //static final String plusIconInner = 'assets/plus_icon_inner.svg';
  static final String plusIconInner = 'assets/counter_plus.svg';
  static final String plusIconInnerRes = 'assets/icon_plus_res.svg';
  static final String plusLeaf = 'assets/plush_leaf.svg';
  //static final String plusIconInner = 'assets/plus_icon_inner.svg';
  static final String plusIconDisable = 'assets/plush_icon_disable.svg';
  static final String minusIcon = 'assets/minus_icon.svg';
  //static final String minusIconInner = 'assets/minus_icon_inner.svg';
  static final String minusIconInner = 'assets/counter_minus.svg';
  static final String minusIconInner_res = 'assets/icon_minum_res.svg';
  static final String minusIconLeaf = 'assets/minus_icon_leaf.svg';
  //static final String minusIconInner = 'assets/minus_icon_inner.svg';
  static final String zoomIcon = 'assets/zoom.svg';
  static final String tickVerifyReferral = 'assets/tick_icon_referral.svg';
  static final String referralErrorIcon = 'assets/referral_error_icon.svg';
  static final String deleteButtonReferral = 'assets/delete_button_referral.svg';
  static final String radioButtonUncheck = 'assets/radio_button_uncheck.svg';
  static final String radioButtonChecked = 'assets/radio_button_checked.svg';

  static final String checkBoxUncheck = 'assets/check_box_unselect.svg';
  static final String checkBoxChecked = 'assets/check_box_selected.svg';
  static final String dummyImageDelete = 'assets/dummy_image_delete.png';
  static final String pharmacyNearby = 'assets/pharmacy_nearby.svg';
  static final String reOrder = 'assets/reorder.svg';
  static final String supermarketNearby = 'assets/super_market.svg';
  static final String restaurantNearby = 'assets/restaurant.svg';

  static final String splashVideo = 'assets/splash_video.mp4';
  static final String referAndEarnSplashVideoAndroid =
      'assets/refer_And_Earn_iOs_Splash.mp4';
  static final String referAndEarnSplashVideoIos = 'assets/ios_Splash.mp4';
  static final String christmasSplashIos =
      'assets/christmas_Splash_Screen_IOS.mp4';
  static final String christmasSplashAndroid =
      'assets/christmas_Splash_Screen_android.mp4';
  static final String crossIcon = 'assets/cross_circle.svg';
//static final String referAndEarnSplashVideoIos = 'assets/splash_video.mp4';
}
