name: network
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  package_info: ^2.0.0
  dio_http2_adapter: ^2.0.0
  data_connection_checker: ^0.3.4
  retrofit: ^3.0.1+1
  logger: any
  json_annotation: ^4.5.0
  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.0.1
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:

